data:
  path: .
  split: .

  transform:
    random_rot: False

model:
  x_to_x: False
  checkpoint:
  guidance: 1
  masif:
    resolution: residue
    nearest_neighbors:
      res_res: 4              # 4 is better than 16
      res_point: 1
    atom_dims: 16
    res_dims: 16              # Number of atom types and dimension of resulting chemical features, default: 6
    hidden_dims: 16           # Number of input features, default: 8
    ori_dim: 16               # Number of hidden units for the orientation score MLP
    radius: 9.0               # Radius to use for the convolution
    dropout: 0.0
    n_layers: 1               # default: 1
    site: False

  model_mean_type: C0  # ['noise', 'C0']
  beta_schedule: sigmoid
  beta_start: 1.e-7
  beta_end: 2.e-3
  v_beta_schedule: cosine
  v_beta_s: 0.01
  num_diffusion_timesteps: 1000
  loss_v_weight: 100.
  sample_time_method: symmetric  # ['importance', 'symmetric']
  perturb_motif_pos: True
  perturb_motif_wid: True
  motif_pos_weight: 0.01
  motif_wid_weight: 100
  time_emb_dim: 1
  time_emb_mode: simple
  center_pos_mode: protein

  node_indicator: True
#  model_type: uni_o2
  num_blocks: 1
  num_layers: 9  # 9
  hidden_dim: 128
  n_heads: 16
  edge_feat_dim: 8  # edge type feat
  num_r_gaussian: 20
  knn: 32 # !
  num_node_types: 8
  act_fn: relu
  norm: True
  cutoff_mode: knn  # [radius, none]
  ew_net_type: global  # [r, m, none]
  num_x2h: 1
  num_h2x: 1
  r_max: 10.
  x2h_out_fc: False
  sync_twoup: False

train:
  seed: 2021
  batch_size: 4
  num_workers: 0
  n_acc_batch: 3
  max_iters: 10000000
  val_freq: 100
  pos_noise_std: 0.1
  max_grad_norm: 8.0
  bond_loss_weight: 1.0
  optimizer:
    type: adam
    lr: 5.e-4
    weight_decay: 0
    beta1: 0.95
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.6
    patience: 10
    min_lr: 1.e-6
